name: Notify Main Repository

on:
  repository_dispatch:
    types: [Auto_Build]  # trigger from submodules repositories

  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Sub module name to check out'
        required: true
      branch_name:
        description: 'Branch to check out in the submodule'
        required: true

run-name: ${{ github.event.client_payload.pull_request_name || 'Manually Trigger Auto Build' }}

concurrency:
  group: ${{ github.event_name }}-${{ github.event.client_payload.repo_name || github.event.inputs.repo_name }}-${{ github.workflow }}-${{ github.event.client_payload.branch_name || github.event.inputs.branch_name }}
  cancel-in-progress: true

jobs:
  PR_Status:
    runs-on: Main_Runner  # Required for .bat script
    steps:
      # This step sets the state to "pending" to indicate that the auto-build process is in progress.  
      # Once the build completes, the status will automatically update to "success" or "failure" based on the outcome.
      # Also it add an link on PR to the current run of auto build
      - name: Set status on submodule PR                          
        uses: actions/github-script@v6
        if: github.event_name == 'repository_dispatch'
        with:
          github-token: ${{ secrets.YOUSSEF_RUNNER }}
          script: |
            await github.rest.repos.createCommitStatus({
              owner: 'YoussefHeshamSalah',
              repo: '${{ github.event.client_payload.repo_name }}',
              sha: '${{ github.event.client_payload.sha_num }}',
              state: "pending",
              context: 'auto-build-status',
              target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            });

  Impbrands_Applications:
    needs: [PR_Status]
    runs-on: Main_Runner  # Required for .bat script
    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
        submodules: recursive
        token: ${{ secrets.YOUSSEF_RUNNER }}
        fetch-depth: 0

    - name: Update submodule to PR branch
      run: |
            .\application\update_submodule.ps1 -SubmoduleName "${{ github.event.client_payload.repo_name || github.event.inputs.repo_name }}" -BranchName "${{ github.event.client_payload.branch_name || github.event.inputs.branch_name }}"

    - name: Run Impbrands-Applications
      run: |
            echo %cd%
            cd .\application\sub_modd_test
            .\example1.bat

  Run_Status:
    needs: [Impbrands_Applications]
    if: always() && github.event_name == 'repository_dispatch'
    runs-on: Main_Runner  # Required for .bat script
    steps:
    - name: Set status on submodule PR
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.YOUSSEF_RUNNER }}
        script: |
          const outcomes = [
            '${{ needs.Impbrands_Applications.result }}',
          ];
          const state = outcomes.every(outcome => outcome === 'success') ? 'success' : 'failure';
          const description = state === 'success' ? 'All scripts ran successfully' : 'One or more scripts failed';
          await github.rest.repos.createCommitStatus({
            owner: 'YoussefHeshamSalah',
            repo: '${{ github.event.client_payload.repo_name }}',
            sha: '${{ github.event.client_payload.sha_num }}',
            state: state,
            context: 'auto-build-status',
            description: description,
            target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          });

          if(state == 'failure'){
            await github.rest.issues.createComment({
              owner: 'YoussefHeshamSalah',
              repo: '${{ github.event.client_payload.repo_name }}',
              issue_number: ${{ github.event.client_payload.pull_request_num }},
              body: `Auto Build Fails, Can be reviewed from (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})`
            });
          }

