name: Notify Main Repository

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: Main_Runner  # This label added to the "HP-ZBPG8-TEST2" machine for TWI_ORG_RUNNER runner
    steps:
      - name: Trigger update-submodules workflow
        run: |
          echo main
